version: '3.9'
services:
  psql_db:
    image: postgres:latest
    container_name: psql_db
    restart: always
    ports:
      - '5432:5432'
    environment:
        POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
        POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
        POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    volumes:
      - ./postgres:/var/lib/postgesql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d ${SPRING_DATASOURCE_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
  app:
    container_name: autopilot_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
    depends_on:
      - psql_db