-- Insert roles
INSERT INTO roles (name) VALUES('ROLE_ADMIN');
INSERT INTO roles (name) VALUES('ROLE_MANAGER');
INSERT INTO roles (name) VALUES ('ROLE_EMPLOYEE');

-- Insert repairs_statuses
INSERT INTO repair_statuses (name) VALUES('PENDING');
INSERT INTO repair_statuses (name) VALUES ('IN_PROGRESS');
INSERT INTO repair_statuses (name) VALUES ('COMPLETED');
INSERT INTO repair_statuses (name) VALUES  ('CANCELED');

-- Insert departments and municipalities
INSERT INTO departments (name) VALUES ('Ahuachapán');
INSERT INTO departments (name) VALUES ('Cabañas');
INSERT INTO departments (name) VALUES ('Chalatenango');
INSERT INTO departments (name) VALUES ('Cuscatlán');
INSERT INTO departments (name) VALUES ('La Libertad');
INSERT INTO departments (name) VALUES ('La Paz');
INSERT INTO departments (name) VALUES ('La Unión');
INSERT INTO departments (name) VALUES ('Morazán');
INSERT INTO departments (name) VALUES ('San Miguel');
INSERT INTO departments (name) VALUES ('San Salvador');
INSERT INTO departments (name) VALUES ('San Vicente');
INSERT INTO departments (name) VALUES ('Santa Ana');
INSERT INTO departments (name) VALUES ('Sonsonate');
INSERT INTO departments (name) VALUES ('Usulután');


INSERT INTO municipalities (name, department_id) VALUES('Atiquizaya', (SELECT id FROM departments WHERE name = 'Ahuachapán'));
INSERT INTO municipalities (name, department_id) VALUES('El Refugio', (SELECT id FROM departments WHERE name = 'Ahuachapán'));
INSERT INTO municipalities (name, department_id) VALUES('San Lorenzo', (SELECT id FROM departments WHERE name = 'Ahuachapán'));
INSERT INTO municipalities (name, department_id) VALUES ('Turín', (SELECT id FROM departments WHERE name = 'Ahuachapán'));
INSERT INTO municipalities (name, department_id) VALUES('Ahuachapán', (SELECT id FROM departments WHERE name = 'Ahuachapán'));
INSERT INTO municipalities (name, department_id) VALUES ('Apaneca', (SELECT id FROM departments WHERE name = 'Ahuachapán'));
INSERT INTO municipalities (name, department_id) VALUES ('Concepción de Ataco', (SELECT id FROM departments WHERE name = 'Ahuachapán'));
INSERT INTO municipalities (name, department_id) VALUES('Tacuba', (SELECT id FROM departments WHERE name = 'Ahuachapán'));
INSERT INTO municipalities (name, department_id) VALUES  ('Guaymango', (SELECT id FROM departments WHERE name = 'Ahuachapán'));
INSERT INTO municipalities (name, department_id) VALUES('Jujutla', (SELECT id FROM departments WHERE name = 'Ahuachapán'));
INSERT INTO municipalities (name, department_id) VALUES('San Francisco Menéndez', (SELECT id FROM departments WHERE name = 'Ahuachapán'));
INSERT INTO municipalities (name, department_id) VALUES('San Pedro Puxtla', (SELECT id FROM departments WHERE name = 'Ahuachapán'));

INSERT INTO municipalities (name, department_id) VALUES ('Guacotecti', (SELECT id FROM departments WHERE name = 'Cabañas'));
INSERT INTO municipalities (name, department_id) VALUES ('San Isidro', (SELECT id FROM departments WHERE name = 'Cabañas'));
INSERT INTO municipalities (name, department_id) VALUES ('Sensuntepeque', (SELECT id FROM departments WHERE name = 'Cabañas'));
INSERT INTO municipalities (name, department_id) VALUES ('Victoria', (SELECT id FROM departments WHERE name = 'Cabañas'));
INSERT INTO municipalities (name, department_id) VALUES ('Dolores', (SELECT id FROM departments WHERE name = 'Cabañas'));
INSERT INTO municipalities (name, department_id) VALUES ('Cinquera', (SELECT id FROM departments WHERE name = 'Cabañas'));
INSERT INTO municipalities (name, department_id) VALUES ('Ilobasco', (SELECT id FROM departments WHERE name = 'Cabañas'));
INSERT INTO municipalities (name, department_id) VALUES ('Jutiapa', (SELECT id FROM departments WHERE name = 'Cabañas'));
INSERT INTO municipalities (name, department_id) VALUES ('Tejutepeque', (SELECT id FROM departments WHERE name = 'Cabañas'));

INSERT INTO municipalities (name, department_id) VALUES ('Citalá', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('La Palma', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES  ('San Ignacio', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('Agua Caliente', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('Dulce Nombre de María', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('El Paraíso', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('La Reina', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('Nueva Concepción', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('San Fernando', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('San Francisco Morazán', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('San Rafael', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('Santa Rita', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('Tejutla', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES  ('Arcatao', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('Azacualpa', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES  ('Cancasque', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES  ('Chalatenango', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES('Comalapa', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('Concepción Quezaltepeque', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES  ('El Carrizal', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('La Laguna', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('Las Vueltas', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('Las Flores', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES('Nombre de Jesús', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('Nueva Trinidad', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES('Ojos de Agua', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES('Potonico', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('San Antonio de la Cruz', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES ('San Antonio Los Ranchos', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES('San Francisco Lempa', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES('San Isidro Labrador', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES  ('San Luis del Carmen', (SELECT id FROM departments WHERE name = 'Chalatenango'));
INSERT INTO municipalities (name, department_id) VALUES  ('San Miguel de Mercedes', (SELECT id FROM departments WHERE name = 'Chalatenango'));

INSERT INTO municipalities (name, department_id) VALUES ('Suchitoto', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES ('San José Guayabal', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES   ('Oratorio de Concepción', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES  ('San Bartolomé Perulapía', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES('San Pedro Perulapán', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES  ('Cojutepeque', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES ('Candelaria', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES ('El Carmen', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES ('El Rosario', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES ('Monte San Juan', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES ('San Cristóbal', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES ('San Rafael Cedros', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES ('San Ramón', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES('Santa Cruz Analquito', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES('Santa Cruz Michapa', (SELECT id FROM departments WHERE name = 'Cuscatlán'));
INSERT INTO municipalities (name, department_id) VALUES ('Tenancingo', (SELECT id FROM departments WHERE name = 'Cuscatlán'));

INSERT INTO municipalities (name, department_id) VALUES('Quezaltepeque', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES ('San Matías', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES ('San Pablo Tacachico', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES ('San Juan Opico', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES ('Ciudad Arce', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES('Colón', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES('Jayaque', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES ('Sacacoyo', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES ('Tepecoyo', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES  ('Talnique', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES ('Antiguo Cuscatlán', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES ('Huizúcar', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES('Nuevo Cuscatlán', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES  ('San José Villanueva', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES('Zaragoza', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES ('Chiltiupán', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES('Jicalapa', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES ('La Libertad', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES ('Tamanique', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES('Teotepeque', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES ('Santa Tecla', (SELECT id FROM departments WHERE name = 'La Libertad'));
INSERT INTO municipalities (name, department_id) VALUES('Comasagua', (SELECT id FROM departments WHERE name = 'La Libertad'));

INSERT INTO municipalities (name, department_id) VALUES ('Cuyultitán', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES('Olocuilta', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES('San Juan Talpa', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES  ('San Luis Talpa', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES ('San Pedro Masahuat', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES  ('Tapalhuaca', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES ('San Francisco Chinameca', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES('El Rosario', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES ('Jerusalén', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES('Mercedes La Ceiba', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES('Paraíso de Osorio', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES  ('San Antonio Masahuat', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES ('San Emigdio', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES ('San Juan Tepezontes', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES('San Luis La Herradura', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES ('San Miguel Tepezontes', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES ('San Pedro Nonualco', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES ('Santa María Ostuma', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES ('Santiago Nonualco', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES ('San Juan Nonualco', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES ('San Rafael Obrajuelo', (SELECT  id FROM departments WHERE name = 'La Paz'));
INSERT INTO municipalities (name, department_id) VALUES('Zacatecoluca', (SELECT  id FROM departments WHERE name = 'La Paz'));

INSERT INTO municipalities (name, department_id) VALUES  ('Anamorós', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES   ('Bolívar', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES ('Concepción de Oriente', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES ('El Sauce', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES('Lislique', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES ('Nueva Esparta', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES  ('Pasaquina', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES ('Polorós', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES  ('San José', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES ('Santa Rosa de Lima', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES('Conchagua', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES ('El Carmen', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES  ('Intipucá', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES ('La Unión', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES ('Meanguera del Golfo', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES ('San Alejo', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES   ('Yayantique', (SELECT  id FROM departments WHERE name = 'La Unión'));
INSERT INTO municipalities (name, department_id) VALUES  ('Yucuaiquín', (SELECT  id FROM departments WHERE name = 'La Unión'));

INSERT INTO municipalities (name, department_id) VALUES ('Arambala',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Cacaopera',(SELECT  id FROM departments WHERE name = 'Morazán'));
                                             
 INSERT INTO municipalities (name, department_id) VALUES                                                    ('Corinto',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('El Rosario',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Joateca',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Jocoaitique',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Meanguera',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Perquín',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('San Fernando',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('San Isidro',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Torola',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Chilanga',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Delicias de Concepción',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('El Divisadero',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Gualococti',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Guatajiagua',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Jocoro',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Lolotiquillo',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Osicala',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('San Carlos',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('San Francisco Gotera',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('San Simón',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Sensembra',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Sociedad',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Yamabal',(SELECT  id FROM departments WHERE name = 'Morazán'));
INSERT INTO municipalities (name, department_id) VALUES ('Yoloaiquín', (SELECT  id FROM departments WHERE name = 'Morazán'));

INSERT INTO municipalities (name, department_id) VALUES ('Ciudad Barrios',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('Sesori',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('Nuevo Edén de San Juan',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('San Gerardo',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('San Luis de la Reina',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('Carolina',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('San Antonio',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('Chapeltique',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('San Miguel',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('Comacarán',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('Uluazapa',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('Moncagua',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('Quelepa',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('Chirilagua',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('Chinameca',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('El Tránsito',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('Lolotique',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('Nueva Guadalupe',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('San Jorge',(SELECT  id FROM departments WHERE name = 'San Miguel'));
INSERT INTO municipalities (name, department_id) VALUES ('San Rafael Oriente', (SELECT  id FROM departments WHERE name = 'San Miguel'));


INSERT INTO municipalities (name, department_id) VALUES ('Aguilares',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('El Paisnal',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Guazapa',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Apopa',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Nejapa',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Cuscatancingo',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Ciudad Delgado',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Ilopango',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('San Martín',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Soyapango',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Tonacatepeque',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Ayutuxtepeque',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Mejicanos',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('San Marcos',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('San Salvador',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Santo Tomás',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Santiago Texacuangos',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Panchimalco',(SELECT  id FROM departments WHERE name = 'San Salvador'));
INSERT INTO municipalities (name, department_id) VALUES ('Rosario de Mora',(SELECT  id FROM departments WHERE name = 'San Salvador'));

INSERT INTO municipalities (name, department_id) VALUES ('Apastepeque',(SELECT  id FROM departments WHERE name = 'San Vicente'));
INSERT INTO municipalities (name, department_id) VALUES ('Santa Clara',(SELECT  id FROM departments WHERE name = 'San Vicente'));
INSERT INTO municipalities (name, department_id) VALUES ('San Ildefonso',(SELECT  id FROM departments WHERE name = 'San Vicente'));
INSERT INTO municipalities (name, department_id) VALUES ('San Esteban Catarina',(SELECT  id FROM departments WHERE name = 'San Vicente'));
INSERT INTO municipalities (name, department_id) VALUES ('San Sebastián',(SELECT  id FROM departments WHERE name = 'San Vicente'));
INSERT INTO municipalities (name, department_id) VALUES ('San Lorenzo',(SELECT  id FROM departments WHERE name = 'San Vicente'));
INSERT INTO municipalities (name, department_id) VALUES ('Santo Domingo',(SELECT  id FROM departments WHERE name = 'San Vicente'));
INSERT INTO municipalities (name, department_id) VALUES ('San Vicente',(SELECT  id FROM departments WHERE name = 'San Vicente'));
INSERT INTO municipalities (name, department_id) VALUES ('Guadalupe',(SELECT  id FROM departments WHERE name = 'San Vicente'));
INSERT INTO municipalities (name, department_id) VALUES ('San Cayetano Istepeque',(SELECT  id FROM departments WHERE name = 'San Vicente'));
INSERT INTO municipalities (name, department_id) VALUES ('Tecoluca',(SELECT  id FROM departments WHERE name = 'San Vicente'));
INSERT INTO municipalities (name, department_id) VALUES ('Tepetitán',(SELECT  id FROM departments WHERE name = 'San Vicente'));
INSERT INTO municipalities (name, department_id) VALUES ('Verapaz', (SELECT  id FROM departments WHERE name = 'San Vicente'));


INSERT INTO municipalities (name, department_id) VALUES ('Masahuat',(SELECT  id FROM departments WHERE name = 'Santa Ana'));
INSERT INTO municipalities (name, department_id) VALUES ('Metapán',(SELECT  id FROM departments WHERE name = 'Santa Ana'));
INSERT INTO municipalities (name, department_id) VALUES ('Santa Rosa Guachipilín',(SELECT  id FROM departments WHERE name = 'Santa Ana'));
INSERT INTO municipalities (name, department_id) VALUES ('Texistepeque',(SELECT  id FROM departments WHERE name = 'Santa Ana'));
INSERT INTO municipalities (name, department_id) VALUES ('Santa Ana',(SELECT  id FROM departments WHERE name = 'Santa Ana'));
INSERT INTO municipalities (name, department_id) VALUES ('Coatepeque',(SELECT  id FROM departments WHERE name = 'Santa Ana'));
INSERT INTO municipalities (name, department_id) VALUES ('El Congo',(SELECT  id FROM departments WHERE name = 'Santa Ana'));
INSERT INTO municipalities (name, department_id) VALUES ('Candelaria de la Frontera',(SELECT  id FROM departments WHERE name = 'Santa Ana'));
INSERT INTO municipalities (name, department_id) VALUES ('Chalchuapa',(SELECT  id FROM departments WHERE name = 'Santa Ana'));
INSERT INTO municipalities (name, department_id) VALUES ('El Porvenir',(SELECT  id FROM departments WHERE name = 'Santa Ana'));
INSERT INTO municipalities (name, department_id) VALUES ('San Antonio Pajonal',(SELECT  id FROM departments WHERE name = 'Santa Ana'));
INSERT INTO municipalities (name, department_id) VALUES ('San Sebastián Salitrillo',(SELECT  id FROM departments WHERE name = 'Santa Ana'));
INSERT INTO municipalities (name, department_id) VALUES ('Santiago de la Frontera', (SELECT  id FROM departments WHERE name = 'Santa Ana'));

INSERT INTO municipalities (name, department_id) VALUES ('Juayúa',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('Nahuizalco',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('Salcoatitán',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('Santa Catarina Masahuat',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('Sonsonate',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('Sonzacate',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('Nahulingo',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('San Antonio del Monte',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('Santo Domingo de Guzmán',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('Armenia',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('Caluco',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('Cuisnahuat',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('Izalco',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('San Julián',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('Santa Isabel Ishuatán',(SELECT  id FROM departments WHERE name = 'Sonsonate'));
INSERT INTO municipalities (name, department_id) VALUES ('Acajutla', (SELECT  id FROM departments WHERE name = 'Sonsonate'));

INSERT INTO municipalities (name, department_id) VALUES ('Alegría',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Berlín',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('El Triunfo',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Estanzuelas',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Jucuapa',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Mercedes Umaña',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Nueva Granada',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('San Buenaventura',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Santiago de María',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('California',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Concepción Batres',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Ereguayquín',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Jucuarán',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Ozatlán',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Santa Elena',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('San Dionisio',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Santa María',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Tecapán',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Usulután',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Jiquilisco',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('Puerto El Triunfo',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('San Agustín',(SELECT  id FROM departments WHERE name = 'Usulután'));
INSERT INTO municipalities (name, department_id) VALUES ('San Francisco Javier', (SELECT  id FROM departments WHERE name = 'Usulután'));

-- Insert brands and models
INSERT INTO brands (name) VALUES ('Toyota');
INSERT INTO brands (name) VALUES ('Honda');
INSERT INTO brands (name) VALUES ('Ford');
INSERT INTO brands (name) VALUES ('Chevrolet');
INSERT INTO brands (name) VALUES ('Nissan');
INSERT INTO brands (name) VALUES ('Hyundai');
INSERT INTO brands (name) VALUES ('Kia');
INSERT INTO brands (name) VALUES ('Mazda');
INSERT INTO brands (name) VALUES ('Subaru');
INSERT INTO brands (name) VALUES ('Jeep');

INSERT INTO models (brand_id, name) VALUES (1, 'Corolla');
INSERT INTO models (brand_id, name) VALUES (1, 'Yaris');
INSERT INTO models (brand_id, name) VALUES (1, 'Camry');
INSERT INTO models (brand_id, name) VALUES (1, 'Prius');
INSERT INTO models (brand_id, name) VALUES (1, 'RAV4');
INSERT INTO models (brand_id, name) VALUES (1, 'Highlander');
INSERT INTO models (brand_id, name) VALUES (1, 'Sienna');
INSERT INTO models (brand_id, name) VALUES (1, 'Tacoma');
INSERT INTO models (brand_id, name) VALUES (1, 'Tundra');
INSERT INTO models (brand_id, name) VALUES (1, '4Runner');
INSERT INTO models (brand_id, name) VALUES (1, 'Sequoia');
INSERT INTO models (brand_id, name) VALUES (1, 'Land Cruiser');
INSERT INTO models (brand_id, name) VALUES (1, 'Avalon');
INSERT INTO models (brand_id, name) VALUES (1, 'C-HR');
INSERT INTO models (brand_id, name) VALUES (1, 'Supra');
INSERT INTO models (brand_id, name) VALUES (1, 'Mirai');
INSERT INTO models (brand_id, name) VALUES (1, 'Venza');

INSERT INTO models (brand_id, name) VALUES (2, 'Civic');
INSERT INTO models (brand_id, name) VALUES (2, 'Accord');
INSERT INTO models (brand_id, name) VALUES (2, 'CR-V');
INSERT INTO models (brand_id, name) VALUES (2, 'HR-V');
INSERT INTO models (brand_id, name) VALUES (2, 'Pilot');
INSERT INTO models (brand_id, name) VALUES (2, 'Odyssey');
INSERT INTO models (brand_id, name) VALUES (2, 'Passport');
INSERT INTO models (brand_id, name) VALUES (2, 'Ridgeline');
INSERT INTO models (brand_id, name) VALUES (2, 'Insight');
INSERT INTO models (brand_id, name) VALUES (2, 'Clarity');
INSERT INTO models (brand_id, name) VALUES (2, 'Fit');
INSERT INTO models (brand_id, name) VALUES (2, 'Civic Type R');
INSERT INTO models (brand_id, name) VALUES (2, 'CR-Z');
INSERT INTO models (brand_id, name) VALUES (2, 'Element');
INSERT INTO models (brand_id, name) VALUES (2, 'FCX Clarity');
INSERT INTO models (brand_id, name) VALUES (2, 'Fit EV');
INSERT INTO models (brand_id, name) VALUES (2, 'S2000');

INSERT INTO models (brand_id, name) VALUES (3, 'Fiesta');
INSERT INTO models (brand_id, name) VALUES (3, 'Focus');
INSERT INTO models (brand_id, name) VALUES (3, 'Fusion');
INSERT INTO models (brand_id, name) VALUES (3, 'Taurus');
INSERT INTO models (brand_id, name) VALUES (3, 'Mustang');
INSERT INTO models (brand_id, name) VALUES (3, 'EcoSport');
INSERT INTO models (brand_id, name) VALUES (3, 'Escape');
INSERT INTO models (brand_id, name) VALUES (3, 'Edge');
INSERT INTO models (brand_id, name) VALUES (3, 'Flex');
INSERT INTO models (brand_id, name) VALUES (3, 'Explorer');
INSERT INTO models (brand_id, name) VALUES (3, 'Expedition');
INSERT INTO models (brand_id, name) VALUES (3, 'Ranger');
INSERT INTO models (brand_id, name) VALUES (3, 'F-100');
INSERT INTO models (brand_id, name) VALUES (3, 'Super Duty (F-250, F-350, F-450)');

INSERT INTO models (brand_id, name) VALUES (4, 'Spark');
INSERT INTO models (brand_id, name) VALUES (4, 'Sonic');
INSERT INTO models (brand_id, name) VALUES (4, 'Cruze');
INSERT INTO models (brand_id, name) VALUES (4, 'Malibu');
INSERT INTO models (brand_id, name) VALUES (4, 'Impala');
INSERT INTO models (brand_id, name) VALUES (4, 'Volt');
INSERT INTO models (brand_id, name) VALUES (4, 'Bolt EV');
INSERT INTO models (brand_id, name) VALUES (4, 'Trax');
INSERT INTO models (brand_id, name) VALUES (4, 'Equinox');
INSERT INTO models (brand_id, name) VALUES (4, 'Blazer');
INSERT INTO models (brand_id, name) VALUES (4, 'Traverse');
INSERT INTO models (brand_id, name) VALUES (4, 'Tahoe');
INSERT INTO models (brand_id, name) VALUES (4, 'Suburban');
INSERT INTO models (brand_id, name) VALUES (4, 'Colorado');
INSERT INTO models (brand_id, name) VALUES (4, 'Silverado');
INSERT INTO models (brand_id, name) VALUES (4, 'Corvette');
INSERT INTO models (brand_id, name) VALUES (4, 'Camaro');
INSERT INTO models (brand_id, name) VALUES (4, 'Express');


INSERT INTO models (brand_id, name) VALUES (5, 'Versa');
INSERT INTO models (brand_id, name) VALUES (5, 'Sentra');
INSERT INTO models (brand_id, name) VALUES (5, 'Altima');
INSERT INTO models (brand_id, name) VALUES (5, 'Maxima');
INSERT INTO models (brand_id, name) VALUES (5, 'LEAF');
INSERT INTO models (brand_id, name) VALUES (5, 'Juke');
INSERT INTO models (brand_id, name) VALUES (5, 'Kicks');
INSERT INTO models (brand_id, name) VALUES (5, 'Rogue Sport');
INSERT INTO models (brand_id, name) VALUES (5, 'Rogue');
INSERT INTO models (brand_id, name) VALUES (5, 'Murano');
INSERT INTO models (brand_id, name) VALUES (5, 'Pathfinder');
INSERT INTO models (brand_id, name) VALUES (5, 'Armada');
INSERT INTO models (brand_id, name) VALUES (5, 'Frontier');
INSERT INTO models (brand_id, name) VALUES (5, 'Titan');
INSERT INTO models (brand_id, name) VALUES (5, 'NV200');
INSERT INTO models (brand_id, name) VALUES (5, 'NV Cargo');
INSERT INTO models (brand_id, name) VALUES (5, 'NV Passenger');

INSERT INTO models (brand_id, name) VALUES (6, 'Accent');
INSERT INTO models (brand_id, name) VALUES (6, 'Elantra');
INSERT INTO models (brand_id, name) VALUES (6, 'Sonata');
INSERT INTO models (brand_id, name) VALUES (6, 'Veloster');
INSERT INTO models (brand_id, name) VALUES (6, 'Ioniq');
INSERT INTO models (brand_id, name) VALUES (6, 'Kona');
INSERT INTO models (brand_id, name) VALUES (6, 'Venue');
INSERT INTO models (brand_id, name) VALUES (6, 'Santa Fe');
INSERT INTO models (brand_id, name) VALUES (6, 'Tucson');
INSERT INTO models (brand_id, name) VALUES (6, 'Nexo');
INSERT INTO models (brand_id, name) VALUES (6, 'Palisade');
INSERT INTO models (brand_id, name) VALUES (6, 'Genesis');

INSERT INTO models (brand_id, name) VALUES (7, 'Rio');
INSERT INTO models (brand_id, name) VALUES (7, 'Forte');
INSERT INTO models (brand_id, name) VALUES (7, 'Optima');
INSERT INTO models (brand_id, name) VALUES (7, 'Cadenza');
INSERT INTO models (brand_id, name) VALUES (7, 'Stinger');
INSERT INTO models (brand_id, name) VALUES (7, 'K5');
INSERT INTO models (brand_id, name) VALUES (7, 'K900');
INSERT INTO models (brand_id, name) VALUES (7, 'Soul');
INSERT INTO models (brand_id, name) VALUES (7, 'Seltos');
INSERT INTO models (brand_id, name) VALUES (7, 'Sportage');
INSERT INTO models (brand_id, name) VALUES (7, 'Sorento');
INSERT INTO models (brand_id, name) VALUES (7, 'Telluride');
INSERT INTO models (brand_id, name) VALUES (7, 'Niro');
INSERT INTO models (brand_id, name) VALUES (7, 'Sedona');
INSERT INTO models (brand_id, name) VALUES (7, 'Carnival');
INSERT INTO models (brand_id, name) VALUES (7, 'EV6');

INSERT INTO models (brand_id, name) VALUES (8, 'Mazda3');
INSERT INTO models (brand_id, name) VALUES (8, 'Mazda5');
INSERT INTO models (brand_id, name) VALUES (8, 'MX-5 Miata');
INSERT INTO models (brand_id, name) VALUES (8, 'CX-3');
INSERT INTO models (brand_id, name) VALUES (8, 'CX-30');
INSERT INTO models (brand_id, name) VALUES (8, 'CX-5');
INSERT INTO models (brand_id, name) VALUES (8, 'CX-9');
INSERT INTO models (brand_id, name) VALUES (8, 'MX-30');

INSERT INTO models (brand_id, name) VALUES (9, 'Impreza');
INSERT INTO models (brand_id, name) VALUES (9, 'WRX');
INSERT INTO models (brand_id, name) VALUES (9, 'Legacy');

INSERT INTO models (brand_id, name) VALUES (10, 'Renegade');
INSERT INTO models (brand_id, name) VALUES (10, 'Compass');
INSERT INTO models (brand_id, name) VALUES (10, 'Cherokee');
INSERT INTO models (brand_id, name) VALUES (10, 'Grand Cherokee');
INSERT INTO models (brand_id, name) VALUES (10, 'Wrangler');
INSERT INTO models (brand_id, name) VALUES (10, 'Gladiator');
INSERT INTO models (brand_id, name) VALUES (10, 'Grand Wagoneer');
INSERT INTO models (brand_id, name) VALUES (10, 'Wagoneer');

-- default branch
INSERT INTO branches  (main, created_at, municipality_id, updated_at, address, email, name, phone) VALUES (true, NOW(), 81, NOW(), 'Calle el Mediterráneo, No. 662 Colonia Jardines de Guadalupe.', 'comunicacionesfya@feyalegria.org.sv', 'Fe y Alegria Antiguo Cuscatlan', '22431282');

-- default user
INSERT INTO users (email, password, name, created_at, updated_at) VALUES ('josiasalvarengaromero@gmail.com','$2a$10$JDQIC24AMy9gN1tNWcOso.2cmoCIvHbdxp1asYclm1BxWKr90.15i', 'Administrator',  NOW(), NOW());
INSERT INTO user_roles (user_id, role_id) VALUES (1, 1);